import 'package:tormenta20/src/shared/entities/magic/magic.dart';
import 'package:tormenta20/src/shared/entities/magic/magic_circles.dart';
import 'package:tormenta20/src/shared/entities/magic/magic_duration.dart';
import 'package:tormenta20/src/shared/entities/magic/magic_execution.dart';
import 'package:tormenta20/src/shared/entities/magic/magic_range.dart';
import 'package:tormenta20/src/shared/entities/magic/magic_school.dart';
import 'package:tormenta20/src/shared/entities/magic/magic_type.dart';

class MagicsService {
  List<Magic> getAllMagics() => _magics;

  final List<Magic> _magics = [
    Magic(
      id: 1,
      name: 'Abençoar Alimentos',
      desc:
          'Você purifica e abençoa uma porção de comida ou dose de bebida. Isso torna um alimento sujo, estragado ou envenenado próprio para consumo.\n Além disso, se for consumido até o final da duração, o alimento oferece 5 PV temporários ou 1 PM temporário (além de quaisquer bônus que já oferecesse).\n\n Bônus de alimentação duram um dia e cada personagem só pode receber um bônus de alimentação por dia. \n\nTruque: o alimento é purificado (não causa nenhum efeito nocivo se estava estragado ou envenenado), mas não fornece bônus ao ser consumido. \n\n+1 PM: aumenta o número de alvos em +1.+1 PM: muda a duração para permanente, o alvo para 1 frasco com água e adiciona componente material (pó de prata no valor de T\$ 5). Em vez do normal, cria um frasco de água benta.',
      circle: firstCircle,
      type: MagicType.Divina,
      school: MagicSchool.Transmutacao,
      execution: MagicExecution.Padrao,
      duration: MagicDuration.Cena,
      range: MagicRange.Curto,
      resistence: 'Nenhuma',
      targetAreaEfect: 'Alimento para 1 criatura',
      publication: 'Edição Jogo do Ano',
    ),
    Magic(
      id: 2,
      name: 'Acalmar Animal',
      desc:
          "O animal fica prestativo em relação a você. Ele não fica sob seu controle, mas percebe suas palavras e ações da maneira mais favorável possível. Você recebe +10 nos testes de Adestramento e Diplomacia que fizer contra o animal. Um alvo hostil ou que esteja envolvido em um combate recebe +5 em seu teste de resistência. Se você ou seus aliados tomarem qualquer ação hostil contra o alvo, a magia é dissipada e ele retorna à atitude que tinha antes (ou piorada, de acordo com o mestre). Se tratar bem o alvo, a atitude pode permanecer mesmo após o término da magia.\n\n+1 PM: muda o alcance para médio.\n\n+1 PM: muda o alvo para 1 monstro ou espírito com Inteligência 1 ou 2.\n\n+2 PM: aumenta o número de alvos em +1.\n\n+5 PM: muda o alvo para 1 monstro ou espírito. Requer 3º círculo.",
      circle: firstCircle,
      type: MagicType.Divina,
      school: MagicSchool.Encantamento,
      execution: MagicExecution.Padrao,
      duration: MagicDuration.Cena,
      range: MagicRange.Curto,
      resistence: 'Vontade anula',
      targetAreaEfect: '1 animal',
      publication: 'Edição Jogo do Ano',
    ),
    Magic(
      id: 3,
      name: 'Açoite Flamejante',
      desc:
          "Um açoite de fogo surge em uma de suas mãos com a qual possa empunhar uma arma (essa mão fica ocupada pela duração da magia). Você pode usar uma ação padrão para causar 2d6 pontos de dano de fogo com o açoite em uma criatura em alcance curto e deixá-la em chamas e enredada enquanto estiver em chamas dessa forma. Passar na resistência reduz o dano à metade e evita as chamas.\n\n+2 PM: muda a execução para movimento.\n\n+2 PM: muda o dano para 4d6. Requer 2° círculo.\n\n+5 PM: muda o dano para 6d6. Requer 3° círculo.",
      circle: firstCircle,
      type: MagicType.Arcana,
      school: MagicSchool.Convocacao,
      execution: MagicExecution.Padrao,
      duration: MagicDuration.Sustentada,
      range: MagicRange.Pessoal,
      resistence: 'Reflexos reduz parcial',
      targetAreaEfect: 'Açoite de chamas criado em sua mão (veja texto)',
      publication: 'Edição Jogo do Ano',
    ),
    Magic(
      id: 4,
      name: 'Adaga Mental',
      desc:
          "Você manifesta e dispara uma adaga imaterial contra a mente do alvo, que sofre 2d6 pontos de dano psíquico e fica atordoado por uma rodada. Se passar no teste de resistência, sofre apenas metade do dano e evita a condição. Uma criatura só pode ficar atordoada por esta magia uma vez por cena.\n\n+1 PM: você lança a magia sem gesticular ou pronunciar palavras (o que permite lançar esta magia de armadura) e a adaga se torna invisível. Se o alvo falhar no teste de resistência, não percebe que você lançou uma magia contra ele.\n\n+2 PM: muda a duração para um dia. Além do normal, você “finca” a adaga na mente do alvo. Enquanto a magia durar, você sabe a direção e localização do alvo, desde que ele esteja no mesmo mundo.\n\n+2 PM: aumenta o dano em +1d6.",
      circle: firstCircle,
      type: MagicType.Arcana,
      school: MagicSchool.Convocacao,
      execution: MagicExecution.Padrao,
      duration: MagicDuration.Instantanea,
      range: MagicRange.Curto,
      resistence: 'Vontade parcial',
      targetAreaEfect: '1 criatura',
      publication: 'Edição Jogo do Ano',
    ),
    Magic(
      id: 5,
      name: 'Alarme',
      desc:
          "Você cria uma barreira protetora invisível que detecta qualquer criatura que tocar ou entrar na área protegida. Ao lançar a magia, você pode escolher quais criaturas podem entrar na área sem ativar seus efeitos. Alarme pode emitir um aviso telepático ou sonoro, decidido quando a magia é lançada. Um aviso telepático alerta apenas você, inclusive acordando-o se estiver dormindo, mas apenas se estiver a até 1km da área protegida. Um aviso sonoro alerta todas as criaturas em alcance longo.\n\n+2 PM: muda o alcance para pessoal. A área é emanada a partir de você.\n\n+5 PM: além do normal, você também percebe qualquer efeito de adivinhação que seja usado dentro da área ou atravesse a área. Você pode fazer um teste oposto de Misticismo contra quem usou o efeito se passar, tem um vislumbre de seu rosto e uma ideia aproximada de sua localização (“três dias de viagem ao norte”, por exemplo).\n\n+9 PM: muda a duração para um dia ou até ser descarregada e a resistência para Vontade anula. Quando um intruso entra na área, você pode descarregar a magia. Se o intruso falhar na resistência, ficará paralisado por 1d4 rodadas. Além disso, pelas próximas 24 horas você e as criaturas escolhidas ganham +10 em testes de Sobrevivência para rastrear o intruso.",
      circle: firstCircle,
      type: MagicType.Arcana,
      school: MagicSchool.Abjuracao,
      execution: MagicExecution.Padrao,
      duration: MagicDuration.UmDia,
      range: MagicRange.Curto,
      resistence: 'nenhuma',
      targetAreaEfect: 'esfera com 9m de raio',
      publication: 'Edição Jogo do Ano',
    ),
    Magic(
      id: 6,
      name: 'Amedrontar',
      desc:
          "O alvo é envolvido por energias sombrias e assustadoras. Se falhar na resistência, fica apavorado por 1 rodada, depois abalado. Se passar, fica abalado por 1d4 rodadas.\n\n+2 PM: alvos que falhem na resistência ficam apavorados por 1d4+1 rodadas, em vez de apenas 1.\n\n+2 PM: muda o alvo para 1 criatura.\n +5 PM: afeta todos os alvos válidos a sua escolha dentro do alcance.",
      circle: firstCircle,
      type: MagicType.Arcana,
      school: MagicSchool.Necromancia,
      execution: MagicExecution.Padrao,
      duration: MagicDuration.Cena,
      range: MagicRange.Curto,
      resistence: 'Vontade parcial',
      targetAreaEfect: '1 animal ou humanoide',
      publication: 'Edição Jogo do Ano',
    ),
    Magic(
      id: 7,
      name: 'Área Escorregadia',
      desc:
          "Esta magia recobre uma superfície com uma substância gordurosa e escorregadia. Criaturas na área devem passar na resistência para não cair. Nas rodadas seguintes, criaturas que tentem movimentar-se pela área devem fazer testes de Acrobacia para equilíbrio (CD 10).\n\nÁrea Escorregadia pode tornar um item escorregadio. Uma criatura segurando um objeto afetado deve passar na resistência para não deixar o item cair cada vez que usá-lo.\n\n+1 PM: aumenta a área em +1 quadrado de 1,5m.\n +2 PM: muda a CD dos testes de Acrobacia para 15.\n\n+5 PM: muda a CD dos testes de Acrobacia para 20.",
      circle: firstCircle,
      type: MagicType.Arcana,
      school: MagicSchool.Convocacao,
      execution: MagicExecution.Padrao,
      duration: MagicDuration.Cena,
      range: MagicRange.Curto,
      resistence: 'Reflexos (veja texto)',
      targetAreaEfect: 'quadrado de 3m ou 1 objeto',
      publication: 'Edição Jogo do Ano',
    ),
    Magic(
      id: 8,
      name: 'Arma Espiritual',
      desc:
          "Você invoca a arma preferida de sua divindade (caso sua divindade possua uma), que surge flutuando a seu lado. Uma vez por rodada, quando você sofre um ataque corpo a corpo, pode usar uma reação para que a arma cause automaticamente 2d6 pontos de dano do tipo da arma — por exemplo, uma espada longa causa dano de corte — no oponente que fez o ataque. Esta se dissipa se você morrer.\n\n+1 PM: além do normal, a arma o protege. Você recebe +1 na Defesa.\n\n+2 PM: aumenta o bônus na Defesa em +1.\n\n +2 PM: muda a duração para sustentada. Além do normal, uma vez por rodada, você pode gastar uma ação livre para fazer a arma acertar automaticamente um alvo adjacente. Se a arma atacar, não poderá contra-atacar até seu próximo turno. Requer 2º círculo.\n\n+2 PM: muda o tipo do dano para essência. Requer 2º círculo.\n\n+2 PM: aumenta o dano causado pela arma em +1d6 (bônus máximo limitado pelo círculo máximo de magia que você pode lançar).\n\n+5 PM: invoca duas armas, permitindo que você contra-ataque (ou ataque, se usar o aprimoramento acima) duas vezes por rodada. Requer 3º círculo.",
      circle: firstCircle,
      type: MagicType.Divina,
      school: MagicSchool.Convocacao,
      execution: MagicExecution.Padrao,
      duration: MagicDuration.Cena,
      range: MagicRange.Pessoal,
      resistence: 'nenhuma',
      targetAreaEfect: 'você',
      publication: 'Edição Jogo do Ano',
    ),
    Magic(
      id: 9,
      name: 'Armadura Arcana',
      desc:
          "Esta magia cria uma película protetora invisível, mas tangível, fornecendo +5 na Defesa. Esse bônus é cumulativo com outras magias, mas não com bônus fornecido por armaduras.\n\n+1 PM: muda a execução para reação. Em vez do normal, quando sofre um ataque, você cria um escudo mágico que fornece +5 na Defesa contra esse ataque (cumulativo com o bônus do efeito básico desta magia e de armaduras).\n\n+2 PM: aumenta o bônus na Defesa em +1.\n\n+2 PM: muda a duração para um dia.",
      circle: firstCircle,
      type: MagicType.Arcana,
      school: MagicSchool.Convocacao,
      execution: MagicExecution.Padrao,
      duration: MagicDuration.Cena,
      range: MagicRange.Pessoal,
      resistence: 'nenhuma',
      targetAreaEfect: 'você',
      publication: 'Edição Jogo do Ano',
    ),
    Magic(
      id: 10,
      name: 'Armamento da Natureza',
      desc:
          "Você fortalece uma arma mundana primitiva (sem custo em T\$, como bordão, clava, funda ou tacape), uma arma natural ou um ataque desarmado. O dano da arma aumenta em um passo e ela é considerada mágica. Ao lançar a, você pode mudar o tipo de dano da arma (escolhendo entre corte, impacto ou perfuração).\n\n +1 PM: fornece +1 nos testes de ataque com a arma.\n +2 PM: muda a execução para ação de movimento.\n\n +3 PM: aumenta o bônus nos testes de ataque em +1.\n\n +5 PM: aumenta o dano da arma em mais um passo.",
      circle: firstCircle,
      type: MagicType.Divina,
      school: MagicSchool.Transmutacao,
      execution: MagicExecution.Padrao,
      duration: MagicDuration.Cena,
      range: MagicRange.Toque,
      resistence: 'nenhuma',
      targetAreaEfect: '1 arma (veja texto)',
      publication: 'Edição Jogo do Ano',
    ),
    Magic(
      id: 11,
      name: 'Aviso',
      desc:
          "Envia um aviso telepático para uma criatura, mesmo que não possa vê-la nem tenha linha de efeito. Escolha um:\nAlerta: o alvo recebe +5 em seu próximo teste de Iniciativa e de Percepção dentro da cena.\nMensagem: o alvo recebe uma mensagem sua de até 25 palavras. Vocês devem ter um idioma em comum para o alvo poder entendê-lo.\nLocalização: o alvo sabe onde você está naquele momento. Se você mudar de posição, ele não saberá.\n\n+1 PM: aumenta o alcance em um fator de 10 (90m para 900m, 900m para 9km e assim por diante).\n\n+1 PM: se escolher mensagem, o alvo pode enviar uma resposta de até 25 palavras para você até o fim de seu próximo turno.\n\n+2 PM: se escolher localização, muda a duração para cena. O alvo sabe onde você está mesmo que você mude de posição.\n\n+3 PM: aumenta o número de alvos em +1.",
      circle: firstCircle,
      type: MagicType.Universal,
      school: MagicSchool.Adivinhacao,
      execution: MagicExecution.Movimento,
      duration: MagicDuration.Instantanea,
      range: MagicRange.Longo,
      resistence: 'nenhuma',
      targetAreaEfect: '1 criatura',
      publication: 'Edição Jogo do Ano',
    ),
    Magic(
      id: 12,
      name: 'Bênção',
      desc:
          "Abençoa seus aliados, que recebem +1 em testes de ataque e rolagens de dano. Bênção anula Perdição.\n\n+1 PM: muda o alvo para 1 cadáver e a duração para 1 semana. O cadáver não se decompõe nem pode ser transformado em morto-vivo.\n\n+2 PM: aumenta os bônus em +1 (bônus máximo limitado pelo círculo máximo de magia que você pode lançar).",
      circle: firstCircle,
      type: MagicType.Divina,
      school: MagicSchool.Encantamento,
      execution: MagicExecution.Padrao,
      duration: MagicDuration.Cena,
      range: MagicRange.Curto,
      resistence: 'nenhuma',
      targetAreaEfect: 'aliados',
      publication: 'Edição Jogo do Ano',
    ),
    Magic(
      id: 13,
      name: 'Caminhos da Natureza',
      desc:
          "Você invoca espíritos da natureza, pedindo que eles abram seu caminho. As criaturas afetadas recebem deslocamento +3m e ignoram penalidades por terreno difícil em terrenos naturais.\n\nTruque: muda o alcance para pessoal e o alvo para você. Em vez do normal, você recebe +5 em testes de Sobrevivência para se orientar.\n\n+1 PM: além do normal, a CD para rastrear os alvos em terreno natural aumenta em +10.\n\n+2 PM: aumenta o bônus de deslocamento em +3m.",
      circle: firstCircle,
      type: MagicType.Divina,
      school: MagicSchool.Convocacao,
      execution: MagicExecution.Padrao,
      duration: MagicDuration.UmDia,
      range: MagicRange.Curto,
      resistence: 'nenhuma',
      targetAreaEfect: 'criaturas escolhidas',
      publication: 'Edição Jogo do Ano',
    ),
    Magic(
      id: 14,
      name: 'Comando',
      desc:
          "Você dá uma ordem irresistível, que o alvo deve ser capaz de ouvir (mas não precisa entender). Se falhar na resistência, ele deve obedecer ao comando em seu próprio turno da melhor maneira possível. Escolha um dos efeitos.\nFuja: o alvo gasta seu turno se afastando de você (usando todas as suas ações).\nLargue: o alvo solta quaisquer itens que esteja segurando e não pode pegá-los novamente até o início de seu próximo turno. Como esta é uma ação livre, ele ainda pode executar outras ações (exceto pegar aquilo que largou).\nPare: o alvo fica pasmo (apenas uma vez por cena).\nSenta: com uma ação livre, o alvo senta no chão (se estava pendurado ou voando, desce até o chão). Ele pode fazer outras ações, mas não se levantar até o início de seu próximo turno.\nVenha: o alvo gasta seu turno se aproximando de você (usando todas as suas ações).\n\n+1 PM: muda o alvo para 1 criatura.\n\n+2 PM: aumenta a quantidade de alvos em +1.",
      circle: firstCircle,
      type: MagicType.Divina,
      school: MagicSchool.Encantamento,
      execution: MagicExecution.Padrao,
      duration: MagicDuration.UmaRodada,
      range: MagicRange.Curto,
      resistence: 'Vontade anula',
      targetAreaEfect: '1 humanoide',
      publication: 'Edição Jogo do Ano',
    ),
    Magic(
      id: 15,
      name: 'Compreensão',
      desc:
          "Essa magia lhe confere compreensão sobrenatural. Você pode tocar um texto e entender as palavras mesmo que não conheça o idioma. Se tocar numa criatura inteligente, pode se comunicar com ela mesmo que não tenham um idioma em comum. Se tocar uma criatura não inteligente, como um animal, pode perceber seus sentimentos. Você também pode gastar uma ação de movimento para ouvir os pensamentos de uma criatura tocada (você “ouve” o que o alvo está pensando), mas um alvo involuntário tem direito a um teste de Vontade para proteger seus pensamentos e evitar este efeito.\n\n+1 PM: muda o alcance para curto.\n\n+2 PM: muda o alcance para curto e o alvo para criaturas escolhidas. Você pode entender todas as criaturas afetadas, mas só pode ouvir os pensamentos de uma por vez.\n\n+2 PM: muda o alvo para 1 criatura. Em vez do normal, pode vasculhar os pensamentos do alvo para extrair informações. O alvo tem direito a um teste de Vontade para anular este efeito. O mestre decide se a criatura sabe ou não a informação que você procura. Requer 2º círculo.\n\n+5 PM: muda o alcance para pessoal e o alvo para você. Em vez do normal, você pode falar, entender e escrever qualquer idioma. Requer 3º círculo.",
      circle: firstCircle,
      type: MagicType.Universal,
      school: MagicSchool.Adivinhacao,
      execution: MagicExecution.Padrao,
      duration: MagicDuration.Cena,
      range: MagicRange.Toque,
      resistence: 'Vontade anula (veja descrição).',
      targetAreaEfect: '1 criatura ou texto',
      publication: 'Edição Jogo do Ano',
    ),
    Magic(
      id: 16,
      name: 'Concentração de Combate',
      desc:
          "Você amplia sua percepção, antecipando movimentos dos inimigos e achando brechas em sua defesa. Quando faz um teste de ataque, você rola dois dados e usa o melhor resultado.\n\n+2 PM: muda a execução para padrão e a duração para cena. Requer 2º círculo.\n\n+5 PM: além do normal, ao atacar você, um inimigo deve rolar dois dados e usar o pior resultado. Requer 3º círculo.\n\n+9 PM: muda a execução para padrão, o alcance para curto, o alvo para criaturas escolhidas e a duração para cena. Requer 4º círculo.\n\n+14 PM: muda a execução para padrão e a duração para um dia. Além do normal, você recebe um sexto sentido que o avisa de qualquer perigo ou ameaça. Você fica imune às condições surpreendido e desprevenido e recebe +10 na Defesa e Reflexos. Requer 5º círculo.",
      circle: firstCircle,
      type: MagicType.Arcana,
      school: MagicSchool.Adivinhacao,
      execution: MagicExecution.Livre,
      duration: MagicDuration.UmaRodada,
      range: MagicRange.Pessoal,
      resistence: 'nenhuma',
      targetAreaEfect: 'você',
      publication: 'Edição Jogo do Ano',
    ),
    Magic(
      id: 17,
      name: 'Conjurar Monstro',
      desc:
          "Você conjura um monstro Pequeno que ataca seus inimigos. Você escolhe a aparência do monstro e o tipo de dano que ele pode causar, entre corte, impacto e perfuração. No entanto, ele não é uma criatura real, e sim um construto feito de energia. Se for destruído, ou quando a magia acaba, desaparece com um brilho, sem deixar nada para trás. Você só pode ter um monstro conjurado por esta magia por vez. O monstro surge em um espaço desocupado a sua escolha dentro do alcance e age no início de cada um de seus turnos, a partir da próxima rodada. O monstro tem deslocamento 9m e pode fazer uma ação de movimento por rodada. Você pode gastar uma ação padrão para dar uma das seguintes ordens a ele.\nMover: o monstro se movimenta o dobro do deslocamento nessa rodada.\nAtacar: o monstro causa 2d4+2 pontos de dano a uma criatura adjacente.\nLançar Magia: o monstro pode servir como ponto de origem para uma magia lançada por você com execução de uma ação padrão ou menor. Ele pode descarregar um Toque Chocante em um inimigo distante, ou mesmo “cuspir” uma Bola de Fogo! Você gasta PM normalmente para lançar a magia.\nOutros usos criativos para monstros conjurados ficam a critério do mestre. O monstro não age sem receber uma ordem. Para efeitos de jogo, o monstro conjurado tem For 2, Des 3 e todos os outros atributos nulos. Ele tem Defesa igual a sua, 20 pontos de vida e usa o seu valor para teste de Reflexos. Ele é imune a efeitos que pedem um teste de Fortitude ou Vontade.\n\n+1 PM: o monstro ganha deslocamento de escalada ou natação igual ao seu deslocamento terrestre.\n\n+1 PM: aumenta o deslocamento do monstro em +3m.\n\n+1 PM: muda o tipo de dano do ataque do monstro para ácido, fogo, frio ou eletricidade.\n\n+2 PM: aumenta os PV do monstro em +10 para cada categoria de tamanho a partir de Pequeno (+10 PV para Pequeno, +20 PV para Médio etc.).\n\n+2 PM: aumenta o tamanho do monstro para Médio. Ele tem For 4, Des 3, 45 PV, deslocamento 12m e seu ataque causa 2d6+6 pontos de dano.\n\n+2 PM: o monstro ganha resistência 5 contra dois tipos de dano (por exemplo, corte e frio).\n\n+4 PM: o monstro ganha uma nova ordem: Arma de Sopro. Para dar essa ordem você gasta 1 PM, e faz o monstro causar o dobro de seu dano de ataque em um cone de 6m a partir de si (Reflexos reduz à metade).\n\n+5 PM: aumenta o tamanho do monstro para Grande. Ele tem For 7, Des 2, 75 PV, deslocamento 12m e seu ataque causa 4d6+10 pontos de dano com 3m de alcance. Requer 2º círculo.\n\n+9 PM: o monstro ganha deslocamento de voo igual ao dobro do deslocamento.\n\n+9 PM: o monstro ganha imunidade contra dois tipos de dano.\n\n+9 PM: aumenta o tamanho do monstro para Enorme. Ele tem For 11, Des 1, 110 PV, deslocamento 15m e seu ataque causa 4d8+15 pontos de dano com 4,5m de alcance. Requer 4º círculo.\n\n+14 PM: aumenta o tamanho do monstro para Colossal. Ele tem For 15, Des 0, 180 PV, deslocamento 15m e seu ataque causa 4d12+20 pontos de dano com 9m de alcance. Requer 5º círculo.\n\n+1 PM: [Ameaças de Arton] em vez de um monstro, você invoca 4 kobolds Pequenos, que têm For 1, Des 1, Def 12, 1 PV cada e causam, cada um, 1d6-1 pontos de dano com uma ordem atacar. Você pode comandar todos os kobolds com a mesma ação padrão, mas eles devem receber o mesmo tipo de ordem e não podem seguir a ordem lançar magia. Você pode usar este aprimoramento mais vezes para aumentar o número de kobolds em +1, mas não pode usá-lo em conjunto com outros aprimoramentos.\n\n+3 PM: [Ameaças de Arton] como acima, mas cada kobold tem For 4, Des 1, Def 19, 15 PV e causa 2d6+1 pontos de dano de corte com uma ordem atacar. Requer 2º círculo.",
      circle: firstCircle,
      type: MagicType.Arcana,
      school: MagicSchool.Convocacao,
      execution: MagicExecution.Completa,
      duration: MagicDuration.Sustentada,
      range: MagicRange.Curto,
      resistence: 'nenhuma',
      targetAreaEfect: '1 criatura conjurada',
      publication: 'Edição Jogo do Ano',
    ),
    Magic(
      id: 18,
      name: 'Consagrar',
      desc:
          "Você enche a área com energia positiva. Pontos de vida curados por efeitos de luz são maximizados dentro da área. Isso também afeta dano causado em mortos-vivos por esses efeitos. Por exemplo, Curar Ferimentos cura automaticamente 18 PV. Esta magia não pode ser lançada em uma área contendo um símbolo visível dedicado a uma divindade que não a sua.\nConsagrar anula Profanar.\n\n+1 PM: além do normal, mortos-vivos na área sofrem –2 em testes e Defesa.\n\n+2 PM: aumenta as penalidades para mortos-vivos em –1. (penalidade máxima limitada pelo círculo máximo de magia que você pode lançar)\n\n+9 PM: muda a execução para 1 hora, a duração para permanente e adiciona componente material (incenso e óleos no valor de T\$ 1.000). Requer 4º círculo.",
      circle: firstCircle,
      type: MagicType.Divina,
      school: MagicSchool.Evocacao,
      execution: MagicExecution.Padrao,
      duration: MagicDuration.UmDia,
      range: MagicRange.Longo,
      resistence: 'nenhuma',
      targetAreaEfect: 'esfera com 9m de raio',
      publication: 'Edição Jogo do Ano',
    ),
    Magic(
      id: 19,
      name: 'Controlar Plantas',
      desc:
          "Esta magia só pode ser lançada em uma área com vegetação. As plantas se enroscam nas criaturas da área. Aquelas que falharem na resistência ficam enredadas. Uma vítima pode se libertar com uma ação padrão e um teste de Acrobacia ou Atletismo. Além disso, a área é considerada terreno difícil. No início de seus turnos, a vegetação tenta enredar novamente qualquer criatura na área, exigindo um novo teste de Reflexos.\n\nTruque: muda a área para alvo de 1 planta e a resistência para nenhuma. Em vez do normal, você pode fazer a planta se mover como se fosse animada. Ela não pode causar dano ou atrapalhar a concentração de um conjurador.\n\n+1 PM: muda a duração para instantânea. Em vez do normal, as plantas na área diminuem, como se tivessem sido podadas. Terreno difícil muda para terreno normal e não fornece camuflagem. Esse efeito dissipa o uso normal de Controlar Plantas.\n\n+1 PM: além do normal, criaturas que falhem na resistência também ficam imóveis.\n\n+2 PM: muda o alcance para pessoal, a área para alvo (você) e a resistência para nenhuma. Em vez do normal, você consegue se comunicar com plantas, que começam com atitude prestativa em relação a você. Além disso, você pode fazer testes de Diplomacia com plantas. Em geral, plantas têm uma percepção limitada de seus arredores e normalmente fornecem respostas simplórias.",
      circle: firstCircle,
      type: MagicType.Divina,
      school: MagicSchool.Transmutacao,
      execution: MagicExecution.Padrao,
      duration: MagicDuration.Cena,
      range: MagicRange.Curto,
      resistence: 'Reflexos anula.',
      targetAreaEfect: 'quadrado com 9m de lado',
      publication: 'Edição Jogo do Ano',
    ),
    Magic(
      id: 20,
      name: 'Criar Elementos',
      desc:
          "Você cria uma pequena porção de um elemento, a sua escolha. Os elementos criados são reais, não mágicos. Elementos físicos devem surgir em uma superfície. Em vez de um cubo, pode- -se criar objetos simples (sem partes móveis) feitos de gelo, terra ou pedra. Água: enche um recipiente de tamanho Minúsculo (como um odre) com água potável ou cria um cubo de gelo de tamanho Minúsculo. Ar: cria um vento fraco em um quadrado de 1,5m. Isso purifica a área de qualquer gás ou fumaça, ou remove névoa por uma rodada. Fogo: cria uma chama que ilumina como uma tocha. Você pode segurá-la na palma de sua mão sem se queimar, ou fazê-la surgir em um quadrado de 1,5m. Se uma criatura ou objeto estiver no quadrado, sofre 1d6 pontos de dano de fogo se falhar num teste de Reflexos, fica em chamas. Terra: cria um cubo de tamanho Minúsculo feito de terra, argila ou pedra.\n\n+1 PM: aumenta a quantidade do elemento em um passo (uma categoria de tamanho para água ou terra, +1 quadrado de 1,5m para ar e fogo).\n\n+1 PM: muda o efeito para alvo 1 criatura ou objeto e a resistência para Reflexos reduz à metade. Se escolher água ou terra, você arremessa o cubo ou objeto criado no alvo, causando 2d4 pontos de dano de impacto. Para cada categoria de tamanho acima de Minúsculo, o dano aumenta em um passo. O cubo se desfaz em seguida.\n\n+1 PM: se escolheu fogo, aumenta o dano inicial de cada chama em +1d6.",
      circle: firstCircle,
      type: MagicType.Divina,
      school: MagicSchool.Convocacao,
      execution: MagicExecution.Padrao,
      duration: MagicDuration.Instantanea,
      range: MagicRange.Curto,
      resistence: 'nenhuma',
      targetAreaEfect: 'elemento escolhido',
      publication: 'Edição Jogo do Ano',
    ),
    Magic(
      id: 21,
      name: 'Criar Ilusão',
      desc:
          "Esta magia cria uma ilusão visual (uma criatura, uma parede...) ou sonora (um grito de socorro, um uivo assustador...). A magia cria apenas imagens ou sons simples, com volume equivalente ao tom de voz normal para cada cubo de 1,5m no efeito. Não é possível criar cheiros, texturas ou temperaturas, nem sons complexos, como uma música ou diálogo. Criaturas e objetos atravessam uma ilusão sem sofrer dano, mas a magia pode, por exemplo, esconder uma armadilha ou inimigo. A magia é dissipada se você sair do alcance.\n\n+1 PM: muda a duração para sustentada. A cada rodada você pode gastar uma ação livre para mover a imagem ou alterar levemente o som, como aumentar o volume ou fazer com que pareça se afastar ou se aproximar, ainda dentro dos limites do efeito. Você pode, por exemplo, criar a ilusão de um fantasma que anda pela sala, controlando seus movimentos. Quando você para de sustentar a magia, a imagem ou som persistem por mais uma rodada antes de a magia se dissipar.\n\n+1 PM: aumenta o efeito da ilusão em +1 cubo de 1,5m.\n\n+1 PM: também pode criar ilusões de imagem e sons combinados.\n\n+1 PM: também pode criar sons complexos com volume máximo equivalente ao que cinco pessoas podem produzir para cada cubo de 1,5m no efeito. Com uma ação livre, você pode alterar o volume do som ou fazê-lo se aproximar ou se afastar dentro do alcance.\n\n+2 PM: também pode criar odores e sensações térmicas, que são percebidos a uma distância igual ao dobro do tamanho máximo do efeito. Por exemplo, uma miragem de uma fogueira com 4 cubos de 1,5m poderia emanar calor e cheiro de queimado a até 12m.\n\n+2 PM: muda o alcance para longo e o efeito para esfera com 30m de raio. Em vez do normal, você cria um som muito alto, equivalente a uma multidão. Criaturas na área lançam magias como se estivessem em uma condição ruim e a CD de testes de Percepção para ouvir aumenta em +10. Requer 2º círculo.\n\n+2 PM: também criar sensações táteis, como texturas criaturas que não saibam que é uma ilusão não conseguem atravessá-la sem passar em um teste de Vontade (objetos ainda a atravessam). A ilusão ainda é incapaz de causar ou sofrer dano. Requer 2º círculo.\n\n+5 PM: muda a duração para sustentada. Além do normal, você pode gastar uma ação livre para modificar livremente a ilusão (mas não pode acrescentar novos aprimoramentos após lançá-la). Requer 3º círculo.",
      circle: firstCircle,
      type: MagicType.Arcana,
      school: MagicSchool.Ilusao,
      execution: MagicExecution.Padrao,
      duration: MagicDuration.Cena,
      range: MagicRange.Medio,
      resistence: 'Vontade desacredita.',
      targetAreaEfect: 'ilusão que se estende a até 4 cubos de 1,5m',
      publication: 'Edição Jogo do Ano',
    ),
    Magic(
      id: 22,
      name: 'Curar Ferimentos',
      desc:
          "Você canaliza luz que recupera 2d8+2 pontos de vida na criatura tocada.\n\nTruque: muda o alvo para 1 morto-vivo. Em vez do normal, causa 1d8 pontos de dano de luz (Vontade reduz à metade).\n\n+1 PM: aumenta a cura em +1d8+1.\n\n+2 PM: também remove uma condição de fadiga do alvo.\n\n+2 PM: muda o alcance para curto.\n\n+5 PM: muda o alcance para curto e o alvo para criaturas escolhidas.",
      circle: firstCircle,
      type: MagicType.Divina,
      school: MagicSchool.Evocacao,
      execution: MagicExecution.Padrao,
      range: MagicRange.Toque,
      duration: MagicDuration.Instantanea,
      resistence: 'nenhuma',
      targetAreaEfect: '1 criatura',
      publication: 'Edição Jogo do Ano',
    ),
    Magic(
      id: 23,
      name: 'Dardo Gélido',
      desc:
          "Você dispara um dardo de gelo contra o alvo, que sofre 2d6 pontos de dano de frio e fica lento por 1 rodada. Passar no teste de resistência reduz o dano à metade e evita a condição.\n\n+1 PM: aumenta o dano em +1d6.\n\n+1 PM: aumenta o número de alvos em +1 (total de alvos limitado pelo círculo máximo de magia que você pode lançar).",
      circle: firstCircle,
      type: MagicType.Arcana,
      school: MagicSchool.Evocacao,
      execution: MagicExecution.Padrao,
      range: MagicRange.Curto,
      duration: MagicDuration.Instantanea,
      resistence: 'Fortitude parcial',
      targetAreaEfect: '1 criatura',
      publication: 'Ameaças de Arton',
    ),
    Magic(
      id: 24,
      name: 'Despedaçar',
      desc:
          "Esta magia emite um som alto e agudo. O alvo sofre 1d8+2 pontos de dano de impacto (ou o dobro disso e ignora RD se for um construto ou objeto mundano) e fica atordoado por uma rodada (apenas uma vez por cena). Um teste de Fortitude reduz o dano à metade e evita o atordoamento.\n\n+2 PM: aumenta o dano em +1d8+2.\n\n+2 PM: muda o alvo para objeto mundano Médio. Requer 2º círculo.\n\n+5 PM: muda o alvo para objeto mundano Grande. Requer 3º círculo.\n\n+9 PM: muda o alvo para objeto mundano Enorme. Requer 4º círculo.\n\n+14 PM: muda o alvo para objeto mundano Colossal. Requer 5º círculo.\n\n+5 PM: muda o alcance para pessoal e a área para esfera com 6m de raio. Todas as criaturas e objetos mundanos na área são afetados.",
      circle: firstCircle,
      type: MagicType.Divina,
      school: MagicSchool.Evocacao,
      execution: MagicExecution.Padrao,
      range: MagicRange.Curto,
      duration: MagicDuration.Instantanea,
      resistence: 'Fortitude parcial',
      targetAreaEfect: '1 criatura ou objeto mundano Pequeno',
      publication: 'Edição Jogo do Ano',
    ),
    Magic(
      id: 25,
      name: 'Detectar Ameaças',
      desc:
          "Você recebe uma intuição aguçada sobre perigos ao seu redor. Quando uma criatura hostil ou armadilha entra na área do efeito, você faz um teste de Percepção (CD determinada pelo mestre de acordo com a situação). Se passar, sabe a origem (criatura ou armadilha), direção e distância do perigo. Se falhar, sabe apenas que o perigo existe.\n\n+1 PM: você descobre também a raça ou espécie e o poder da criatura detectada (determinado pela aura dela). Criaturas de 1º a 6º nível ou ND geram aura tênue, criaturas de 7º a 12º nível ou ND geram aura moderada e criaturas de 13º ao 20º nível ou ND geram aura poderosa. Criaturas acima do 20º nível ou ND geram aura avassaladora.\n\n+2 PM: além do normal, você não fica surpreendido contra perigos detectados com sucesso e recebe +5 em testes de resistência contra armadilhas. Requer 2º círculo.",
      circle: firstCircle,
      type: MagicType.Divina,
      school: MagicSchool.Adivinhacao,
      execution: MagicExecution.Padrao,
      range: MagicRange.Pessoal,
      duration: MagicDuration.Cena,
      resistence: 'nenhuma',
      targetAreaEfect: 'esfera com 18m de raio',
      publication: 'Edição Jogo do Ano',
    ),
    Magic(
      id: 26,
      name: 'Detonação Congelante',
      desc:
          "Você emite uma onda de frio extremo que cobre a área de gelo. Criaturas na área sofrem 2d6 pontos de dano de frio e ficam enredadas e imóveis por 1d4 rodadas. Passar no teste de resistência reduz o dano pela metade e deixa a criatura enredada por uma rodada. Uma criatura voadora que fica imóvel começa a cair no início do seu turno.\n\n+1 PM: aumenta o dano em +1d6.\n\n+2 PM: muda a duração para sustentada. Ao invés do normal, você emite uma aura de frio constante em alcance curto. Uma criatura que entre na área ou inicie seu turno dentro dela sofre 2d6 pontos de dano de frio e fica enredada e imóvel por uma rodada. Passar no teste de resistência reduz o dano pela metade, evita a condição imóvel e faz com que a criatura não possa mais ficar imóvel por esta magia nesta cena. Requer 2º círculo.",
      circle: firstCircle,
      type: MagicType.Arcana,
      school: MagicSchool.Evocacao,
      execution: MagicExecution.Padrao,
      range: MagicRange.Pessoal,
      duration: MagicDuration.Instantanea,
      resistence: 'Fortitude parcial',
      targetAreaEfect: 'esfera de 6m',
      publication: 'Dragão Brasil',
    ),
    Magic(
      id: 27,
      name: 'Disfarce Ilusório',
      desc:
          "Você muda a aparência do alvo, incluindo seu equipamento. Isso inclui altura, peso, tom de pele, cor de cabelo, timbre de voz etc. O alvo recebe +10 em testes de Enganação para disfarce. O alvo não recebe novas habilidades (você pode ficar parecido com outra raça, mas não ganhará as habilidades dela), nem modifica o equipamento (uma espada longa disfarçada de bordão continua funcionando e causando dano como uma espada).\n\nTruque: muda o alcance para toque, o alvo para 1 criatura e a duração para 1 semana. Em vez do normal, você faz uma pequena alteração na aparência do alvo, como deixar o nariz vermelho ou fazer brotar um gerânio no alto da cabeça. A mudança é inofensiva, mas persistente — se a flor for arrancada, por exemplo, outra nascerá no local.\n\n+1 PM: muda o alcance para curto e o alvo para 1 objeto. Você pode, por exemplo, transformar pedaços de ferro em moedas de ouro. Você recebe +10 em testes de Enganação para falsificação.\n\n+2 PM: muda o alcance para curto e o alvo para 1 criatura. Uma criatura involuntária pode anular o efeito com um teste de Vontade.\n\n+2 PM: a ilusão inclui odores e sensações. Isso muda o bônus em testes de Enganação para disfarce para +20.\n\n+3 PM: muda o alcance para curto e o alvo para criaturas escolhidas. Cada criatura pode ter uma aparência diferente. Criaturas involuntárias podem anular o efeito com um teste de Vontade. Requer 2º círculo.",
      circle: firstCircle,
      type: MagicType.Arcana,
      school: MagicSchool.Ilusao,
      execution: MagicExecution.Completa,
      range: MagicRange.Pessoal,
      duration: MagicDuration.Cena,
      resistence: 'Vontade desacredita',
      targetAreaEfect: 'você',
      publication: 'Edição Jogo do Ano',
    ),
    Magic(
      id: 28,
      name: 'Disparo Gélido',
      desc:
          "Você dispara um dardo de neve e gelo contra o alvo, que causa 2d8+2 pontos de dano de frio.\n\n+1 PM: aumenta o dano em +1d8+1.\n\n+1 PM: muda a resistência para Fortitude parcial. Se passar, a criatura reduz o dano à metade; se falhar, fica lenta até o final da cena.",
      circle: firstCircle,
      type: MagicType.Arcana,
      school: MagicSchool.Evocacao,
      execution: MagicExecution.Padrao,
      range: MagicRange.Medio,
      duration: MagicDuration.Instantanea,
      resistence: 'Fortitude reduz à metade',
      targetAreaEfect: '1 criatura',
      publication: 'Dragão Brasil',
    ),
    Magic(
      id: 29,
      name: 'Enfeitiçar',
      desc:
          "O alvo fica enfeitiçado (veja a página 394). Um alvo hostil ou que esteja envolvido em um combate recebe +5 em seu teste de resistência. Se você ou seus aliados tomarem qualquer ação hostil contra o alvo, a magia é dissipada e o alvo retorna à atitude que tinha antes (ou piorada, de acordo com o mestre).\n\n+2 PM: em vez do normal, você sugere uma ação para o alvo e ele obedece. A sugestão deve ser feita de modo que pareça aceitável, a critério do mestre. Pedir ao alvo que pule de um precipício, por exemplo, dissipa a magia. Já sugerir a um guarda que descanse um pouco, de modo que você e seus aliados passem por ele, é aceitável. Quando o alvo executa a ação, a magia termina. Você pode determinar uma condição específica para a sugestão: por exemplo, que um rico mercador doe suas moedas para o primeiro mendigo que encontrar.\n\n+5 PM: muda o alvo para 1 espírito ou monstro. Requer 3º círculo.\n\n+5 PM: afeta todos os alvos dentro do alcance.",
      circle: firstCircle,
      type: MagicType.Arcana,
      school: MagicSchool.Encantamento,
      execution: MagicExecution.Padrao,
      range: MagicRange.Curto,
      duration: MagicDuration.Cena,
      resistence: 'Vontade anula',
      targetAreaEfect: '1 humanoide',
      publication: 'Edição Jogo do Ano',
    ),
    Magic(
      id: 30,
      name: 'Escudo da Fé',
      desc:
          "Um escudo místico se manifesta momentaneamente para bloquear um golpe. O alvo recebe +2 na Defesa.\n\n+1 PM: muda a execução para ação padrão, o alcance para toque e a duração para cena.\n\n+1 PM: também fornece ao alvo camuflagem leve contra ataques à distância.\n\n+2 PM: aumenta o bônus na Defesa em +1.\n\n+2 PM: muda a execução para ação padrão, o alcance para toque e a duração para cena. A magia cria uma conexão mística entre você e o alvo. Além do efeito normal, o alvo sofre metade do dano por ataques e efeitos a outra metade do dano é transferida a você. Se o alvo sair de alcance curto de você, a é dissipada. Requer 2º círculo.\n\n+3 PM: muda a duração para um dia. Requer 2º círculo.",
      circle: firstCircle,
      type: MagicType.Divina,
      school: MagicSchool.Abjuracao,
      execution: MagicExecution.Reacao,
      range: MagicRange.Curto,
      duration: MagicDuration.UmTurno,
      resistence: 'nenhuma',
      targetAreaEfect: '1 criatura',
      publication: 'Edição Jogo do Ano',
    ),
    Magic(
      id: 31,
      name: 'Escuridão',
      desc:
          "O alvo emana sombras em uma área com 6m de raio. Criaturas dentro da área recebem camuflagem leve por escuridão leve. As sombras não podem ser iluminadas por nenhuma fonte de luz natural. O objeto pode ser guardado (em um bolso, por exemplo) para interromper a escuridão, que voltará a funcionar caso o objeto seja revelado. Se lançar a magia num objeto de uma criatura involuntária, ela tem direito a um teste de Vontade para anulá-la. Escuridão anula Luz.\n\n+1 PM: aumenta a área da escuridão em +1,5m de raio.\n\n+2 PM: muda o efeito para fornecer camuflagem total por escuridão total. As sombras bloqueiam a visão na área e através dela.\n\n+2 PM: muda o alvo para 1 criatura e a resistência para Fortitude parcial. Você lança a magia nos olhos do alvo, que fica cego pela cena. Se passar na resistência, fica cego por 1 rodada. Requer 2º círculo.\n\n+3 PM: muda a duração para um dia.\n\n+5 PM: muda o alcance para pessoal e o alvo para você. Em vez do normal, você é coberto por sombras, recebendo +10 em testes de Furtividade e camuflagem leve. Requer 2º círculo.",
      circle: firstCircle,
      type: MagicType.Universal,
      school: MagicSchool.Necromancia,
      execution: MagicExecution.Padrao,
      range: MagicRange.Curto,
      duration: MagicDuration.Cena,
      resistence: 'Vontade anula (veja texto)',
      targetAreaEfect: '1 objeto',
      publication: 'Edição Jogo do Ano',
    ),
    Magic(
      id: 32,
      name: 'Explosão de Chamas',
      desc:
          "Um leque de chamas irrompe de suas mãos, causando 2d6 pontos de dano de fogo às criaturas na área.\n\nTruque: muda o alcance para curto, a área para alvo de 1 objeto e a resistência para Reflexos anula. Você gera uma pequena explosão que não causa dano mas pode acender uma vela, tocha ou fogueira. Também pode fazer um objeto inflamável com RD 0 (como uma corda ou pergaminho) ficar em chamas. Uma criatura em posse de um objeto pode evitar esse efeito se passar no teste de resistência.\n\n+1 PM: aumenta o dano em +1d6.\n\n+1 PM: muda a resistência para Reflexos parcial. Se passar, a criatura reduz o dano à metade se falhar, fica em chamas (veja Condições, na página 394).",
      circle: firstCircle,
      type: MagicType.Arcana,
      school: MagicSchool.Evocacao,
      execution: MagicExecution.Padrao,
      range: MagicRange.Pessoal,
      duration: MagicDuration.Instantanea,
      resistence: 'Reflexos reduz à metade',
      targetAreaEfect: 'cone de 6m',
      publication: 'Edição Jogo do Ano',
    ),
    Magic(
      id: 33,
      name: 'Geiser Cáustico',
      desc:
          "O solo explode em ácido corrosivo, causando 2d6 pontos de dano de ácido em todas as criaturas e objetos livres na área.\n\n+1 PM: aumenta o dano em +1d6.\n\n+2 PM: Além do normal, o solo continua borbulhando em ácido venenoso até o final da cena, tornando-se terreno difícil. Qualquer criatura que entre na área ou comece o turno dentro dela sofre 2d6 pontos de dano de ácido (sem direito a teste de resistência).",
      circle: firstCircle,
      type: MagicType.Arcana,
      school: MagicSchool.Evocacao,
      execution: MagicExecution.Padrao,
      range: MagicRange.Medio,
      duration: MagicDuration.Instantanea,
      resistence: 'Reflexos reduz à metade',
      targetAreaEfect: 'cilindro com 3m de diâmetro e 3m de altura',
      publication: 'Dragão Brasil',
    ),
    Magic(
      id: 34,
      name: 'Hipnotismo',
      desc:
          "Suas palavras e movimentos ritmados deixam o alvo fascinado. Esta magia só afeta criaturas que possam perceber você. Se usar esta magia em combate, o alvo recebe +5 em seu teste de resistência. Se a criatura passar, fica imune a este efeito por um dia.\n\nTruque: muda a duração para 1 rodada. Em vez de fascinado, o alvo fica pasmo (apenas uma vez por cena).\n\n+1 PM: como o normal, mas alvos que passem na resistência não sabem que foram vítimas de uma magia.\n\n+2 PM: muda o alvo para animais ou humanoides escolhidos.\n\n+2 PM: muda a duração para sustentada.\n\n+2 PM: também afeta espíritos e monstros na área. Requer 2º círculo.\n\n+5 PM: também afeta construtos, espíritos, monstros e mortos-vivos na área. Requer 3º círculo.",
      circle: firstCircle,
      type: MagicType.Arcana,
      school: MagicSchool.Encantamento,
      execution: MagicExecution.Padrao,
      range: MagicRange.Curto,
      duration: MagicDuration.Umd4Rodadas,
      resistence: 'Vontade anula',
      targetAreaEfect: '1 animal ou humanoide',
      publication: 'Edição Jogo do Ano',
    ),
  ];
}
